export default Object.freeze({
  APP: "App",
  AUTH: "Auth",
  CAMERA: "Caméra",
  LISTING: "Accueil",
  LISTING_DETAILS: "Ce repas",
  LISTING_EDIT: "Poster",
  LOGIN: "Se connecter",
  MESSAGES: "Messages",
  MYACCOUNT: "Mon compte",
  MYBALANCE: "Ma balance",
  MYHISTORY: "Mon historique",
  MYLISTINGS: "Mes repas",
  MYPROFILE: "Mon profil",
  MYSETTINGS: "Réglages",
  MYSEARCH: "Recherche",
  MYLOCATION: "Localisation",
  REGISTER: "S'inscrire",
});
